const localPlayersData = [
    {
        "id": 1,
        "name": "Joan García",
        "position": "POR",
        "number": 1,
        "salary": 4000000,
        "value": 25000000,
        "goals": 0,
        "assists": 0,
        "yellowCards": 2,
        "redCards": 0,
        "injured": false,
        "injuryDesc": null,
        "image": "https://img.a.transfermarkt.technology/portrait/header/646750-1692261623.jpg?lm=1"
    },
    {
        "id": 25,
        "name": "Wojciech Szczęsny",
        "position": "POR",
        "number": 25,
        "salary": 3000000,
        "value": 5000000,
        "goals": 0,
        "assists": 0,
        "yellowCards": 0,
        "redCards": 0,
        "injured": false,
        "injuryDesc": null,
        "image": "https://img.a.transfermarkt.technology/portrait/header/44058-1692261623.jpg?lm=1"
    },
    {
        "id": 4,
        "name": "Ronald Araujo",
        "position": "DEF",
        "number": 4,
        "salary": 7000000,
        "value": 70000000,
        "goals": 2,
        "assists": 0,
        "yellowCards": 7,
        "redCards": 1,
        "injured": false,
        "injuryDesc": null,
        "image": "https://img.a.transfermarkt.technology/portrait/header/356026-1692262597.jpg?lm=1"
    },
    {
        "id": 2,
        "name": "Pau Cubarsí",
        "position": "DEF",
        "number": 2,
        "salary": 3500000,
        "value": 50000000,
        "goals": 1,
        "assists": 2,
        "yellowCards": 3,
        "redCards": 0,
        "injured": false,
        "injuryDesc": null,
        "image": "https://img.a.transfermarkt.technology/portrait/header/962110-1706698188.jpg?lm=1"
    },
    {
        "id": 23,
        "name": "Jules Koundé",
        "position": "DEF",
        "number": 23,
        "salary": 6500000,
        "value": 50000000,
        "goals": 2,
        "assists": 5,
        "yellowCards": 4,
        "redCards": 0,
        "injured": false,
        "injuryDesc": null,
        "image": "https://img.a.transfermarkt.technology/portrait/header/411975-1692262529.jpg?lm=1"
    },
    {
        "id": 3,
        "name": "Alejandro Balde",
        "position": "DEF",
        "number": 3,
        "salary": 4000000,
        "value": 45000000,
        "goals": 1,
        "assists": 6,
        "yellowCards": 2,
        "redCards": 0,
        "injured": false,
        "injuryDesc": null,
        "image": "https://img.a.transfermarkt.technology/portrait/header/636682-1692262483.jpg?lm=1"
    },
    {
        "id": 24,
        "name": "Eric García",
        "position": "DEF",
        "number": 24,
        "salary": 4000000,
        "value": 20000000,
        "goals": 1,
        "assists": 1,
        "yellowCards": 3,
        "redCards": 0,
        "injured": false,
        "injuryDesc": null,
        "image": "https://img.a.transfermarkt.technology/portrait/header/466794-1692262529.jpg?lm=1"
    },
    {
        "id": 8,
        "name": "Pedri",
        "position": "MIG",
        "number": 8,
        "salary": 6000000,
        "value": 85000000,
        "goals": 5,
        "assists": 8,
        "yellowCards": 3,
        "redCards": 0,
        "injured": false,
        "injuryDesc": null,
        "image": "https://img.a.transfermarkt.technology/portrait/header/683840-1692262279.jpg?lm=1"
    },
    {
        "id": 6,
        "name": "Gavi",
        "position": "MIG",
        "number": 6,
        "salary": 5000000,
        "value": 90000000,
        "goals": 3,
        "assists": 4,
        "yellowCards": 8,
        "redCards": 0,
        "injured": false,
        "injuryDesc": null,
        "image": "https://img.a.transfermarkt.technology/portrait/header/646740-1692262243.jpg?lm=1"
    },
    {
        "id": 20,
        "name": "Dani Olmo",
        "position": "MIG",
        "number": 20,
        "salary": 8000000,
        "value": 60000000,
        "goals": 9,
        "assists": 8,
        "yellowCards": 2,
        "redCards": 0,
        "injured": false,
        "injuryDesc": null,
        "image": "https://img.a.transfermarkt.technology/portrait/header/246002-1681313411.jpg?lm=1"
    },
    {
        "id": 17,
        "name": "Marc Casadó",
        "position": "MIG",
        "number": 17,
        "salary": 2000000,
        "value": 35000000,
        "goals": 1,
        "assists": 5,
        "yellowCards": 4,
        "redCards": 0,
        "injured": false,
        "injuryDesc": null,
        "image": "https://img.a.transfermarkt.technology/portrait/header/746733-1692262243.jpg?lm=1"
    },
    {
        "id": 21,
        "name": "Frenkie de Jong",
        "position": "MIG",
        "number": 21,
        "salary": 18000000,
        "value": 65000000,
        "goals": 2,
        "assists": 3,
        "yellowCards": 5,
        "redCards": 0,
        "injured": true,
        "injuryDesc": "Molèsties musculars, baixa per 2 setmanes",
        "image": "https://img.a.transfermarkt.technology/portrait/header/324110-1692262203.jpg?lm=1"
    },
    {
        "id": 16,
        "name": "Fermín López",
        "position": "MIG",
        "number": 16,
        "salary": 2500000,
        "value": 35000000,
        "goals": 6,
        "assists": 3,
        "yellowCards": 4,
        "redCards": 0,
        "injured": false,
        "injuryDesc": null,
        "image": "https://img.a.transfermarkt.technology/portrait/header/937085-1692262174.jpg?lm=1"
    },
    {
        "id": 19,
        "name": "Lamine Yamal",
        "position": "DEL",
        "number": 19,
        "salary": 5000000,
        "value": 150000000,
        "goals": 16,
        "assists": 13,
        "yellowCards": 2,
        "redCards": 0,
        "injured": false,
        "injuryDesc": null,
        "image": "https://img.a.transfermarkt.technology/portrait/header/937086-1709543940.jpg?lm=1"
    },
    {
        "id": 9,
        "name": "Robert Lewandowski",
        "position": "DEL",
        "number": 9,
        "salary": 13000000,
        "value": 10000000,
        "goals": 22,
        "assists": 5,
        "yellowCards": 3,
        "redCards": 0,
        "injured": false,
        "injuryDesc": null,
        "image": "https://img.a.transfermarkt.technology/portrait/header/38253-1701118759.jpg?lm=1"
    },
    {
        "id": 11,
        "name": "Raphinha",
        "position": "DEL",
        "number": 11,
        "salary": 6500000,
        "value": 70000000,
        "goals": 14,
        "assists": 15,
        "yellowCards": 3,
        "redCards": 0,
        "injured": false,
        "injuryDesc": null,
        "image": "https://img.a.transfermarkt.technology/portrait/header/411295-1692261905.jpg?lm=1"
    },
    {
        "id": 7,
        "name": "Marcus Rashford",
        "position": "DEL",
        "number": 7,
        "salary": 10000000,
        "value": 60000000,
        "goals": 8,
        "assists": 4,
        "yellowCards": 1,
        "redCards": 0,
        "injured": false,
        "injuryDesc": null,
        "image": "https://img.a.transfermarkt.technology/portrait/header/258923-1692261905.jpg?lm=1"
    }
];
